// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WFandSqliteEFver1.Data;

#nullable disable

namespace WFandSqliteEFver1.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    partial class SqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WFandSqliteEFver1.Data.Gift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kolejka PIKO",
                            Name = "Kolejka",
                            Price = 23.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kolejka PIKO",
                            Name = "Kolejka2",
                            Price = 23.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kolejka PIKO",
                            Name = "Kolejka3",
                            Price = 12m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kolejka PIKO",
                            Name = "Kolejka4",
                            Price = 44.89m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Kolejka PIKO",
                            Name = "Kolejka5",
                            Price = 11.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
