// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppMysqlEF.Models;

#nullable disable

namespace WebAppMysqlEF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebAppMysqlEF.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Jak zawsze nie rdzewieje",
                            Name = "Fiat",
                            Price = 7000m,
                            Year = 2001
                        },
                        new
                        {
                            Id = 2,
                            Description = "Jak zawsze rdzewieje",
                            Name = "Opel",
                            Price = 23000m,
                            Year = 2019
                        },
                        new
                        {
                            Id = 3,
                            Description = "Jak zawsze nie rdzewieje",
                            Name = "VW",
                            Price = 33000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            Description = "....",
                            Name = "Seat",
                            Price = 17000m,
                            Year = 2017
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
